### ISSUE TITLE
Gitlab Pipeline Minutes Adding Up Too Fast

### ISSUE THREAD

**Issue by morganhyland** [leonstafford/static-html-output#145]
I'm using Static HTML Output Version 6.6.12 to export to GitLab. It's working great, except the GitLab pipeline storage adds up really fast, and so do the pipeline minutes.

After 4 deploys of a 157mb site (only 14 pages), I'm at 325.80 GiB in Artifacts, and around 50 pipeline minutes per deploy. 

Did you solve this in a more recent build?

I tried the latest build (6.6.21) but it doesn't work. It doesn't catch all my pages, including the homepage.

The plugin generates this GitLab CI config file (.gitlab-ci.yml). Maybe this needs to be changed?

```yaml
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
```
